### ISSUE TITLE
Split the configuration doc and review them again

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/docs#1043]
The configuration is really large right now, I think we can split it by modules or nodes:

https://docs.greptime.com/user-guide/operations/configuration

And we must review the configuration when v0.9 is released.

**Comment by nicecui** [comment]
The documentation for configuration file options is not intended for users to read options one by one, but to facilitate searching for certain within a single page, so configuration documents are usually large and list all options. For example, the documentation of [MongoDB's configuration file options](https://www.mongodb.com/docs/manual/reference/configuration-options/).

So we don't need to split it. I think we need to [wrap the page navigation](https://github.com/GreptimeTeam/docs/issues/1034) to let users find a certain option conveniently.

**Comment by nicecui** [comment]
I will check the options for v0.9 manually, and hoping we can just [link the configuration to Github](https://github.com/GreptimeTeam/greptimedb/issues/4344) in the future.
