### ISSUE TITLE
User guide for table sharding

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/docs#1046]
We currently offer a table-sharding contributor guide at https://docs.greptime.com/contributor-guide/frontend/table-sharding#table-sharding. 
However, a user guide for table-sharding is absent. It would be beneficial to provide a table-sharding user guide for cluster users, covering:

* Explanation of greptimedb table-sharding functionality
* Instructions on table partitioning in GreptimeDB with examples
* Guidelines for managing table shardings

**Comment by killme2008** [comment]
@waynexia Assign to you, but maybe @fengjiachun or @WenyXu can help

**Comment by nicecui** [comment]
Maybe we can add the partition guides to this [cluster document](https://docs.greptime.com/user-guide/cluster).

**Comment by nicecui** [comment]
https://docs.greptime.com/nightly/user-guide/administration/manage-data/table-sharding
