### ISSUE TITLE
Update docs for feat: Add functionality to the Opentelemetry write interface to extract fields from attr to top-level data. 

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/docs#1227]
A document change request is generated from https://github.com/GreptimeTeam/greptimedb/pull/4859

**Comment by paomian** [comment]
https://github.com/GreptimeTeam/docs/pull/1211

**Comment by paomian** [comment]
https://github.com/GreptimeTeam/docs/pull/1234
