### ISSUE TITLE
Adds documents for geohash data type

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/docs#1231]
Needs documents for geohash data type, it's only in https://docs.greptime.com/reference/sql/functions/geo/

Maybe needs a link from https://docs.greptime.com/reference/sql/data-types/

**Comment by sunng87** [comment]
We don't really have data types for geo data. We use primitives for coordinates and string for hash results.

**Comment by killme2008** [comment]
@sunng87 Of course, I knew it. But we can add a reference such as even though we don't support data type for geo data, but we have geospatial functions like that. The data type document is the document that you want to know what data types which the GreptimeDB supports right now, it's worthy mentioning it there.
