### ISSUE TITLE
Error when executing ALTER TABLE the SET option

### ISSUE THREAD

**Issue by IrisesD** [GreptimeTeam/docs#1269]
## Error when executing ALTER TABLE the SET option

I tried using the example SET statements in ALTER TABLE options in the document: `ALTER TABLE monitor SET 'ttl'='1d';`
However the standalone mode server I used reported with the error message:
`(InvalidSyntax): sql parser error: expect keyword ADD or DROP or MODIFY or RENAME after ALTER TABLE, found SET`

It seems that this option is still not supported in this version of Greptime.

Is there any inconsistency between the document and the code? The version of Greptime I used is v0.9.5.

**Comment by nicecui** [comment]
Thanks for your feedback. It’s in the Nightly release, you can try this feature in v0.10.0-nightly-20241104.

**Comment by nicecui** [comment]
Hello, v0.10.2 has been released, you can use this option in v0.10.2.

**Comment by nicecui** [comment]
This issue has been resolved, so I closed it. If you have any other questions, welcome to submit a new issue.
