### ISSUE TITLE
Improve the CN document description

### ISSUE THREAD

**Issue by daviderli614** [GreptimeTeam/docs#1405]
- https://docs.greptime.cn/user-guide/concepts/why-greptimedb#%E5%B0%8F%E7%BB%93
The version of GreptimeDB describe in the document is too old
![image](https://github.com/user-attachments/assets/cdef5112-40bb-49f6-aee4-23febd765c90)

- https://docs.greptime.cn/user-guide/concepts/architecture
Maybe is **datanode** ？

![image](https://github.com/user-attachments/assets/37d04997-adae-491a-a8da-2c4198da426c)

- https://docs.greptime.cn/user-guide/concepts/key-concepts
Is the font style correct?
![image](https://github.com/user-attachments/assets/3f622a56-fcee-43d1-894b-511095c2a288)

- https://docs.greptime.cn/user-guide/ingest-data/for-observerbility/vector#%E9%9B%86%E6%88%90
`type=greptimedb` is old version, reference: https://vector.dev/docs/reference/configuration/sinks/greptimedb_metrics/
Can be changed to `greptimedb_metrics`.

- https://docs.greptime.cn/user-guide/ingest-data/for-iot/grpc-sdks/go#%E5%AE%89%E8%A3%85
The SDK version too old.
![image](https://github.com/user-attachments/assets/64945a2c-1b3e-4729-a82c-505dd9fcc8d6)

- https://docs.greptime.cn/user-guide/administration/upgrade
The version too old.

**Comment by nicecui** [comment]
Thank you for your feedback.

1. The following content has been updated:
- Why GreptimeDB
- typos
- SDK version

2. The example versions in the upgrade documentation is exactly the corresponding versions. If the example steps have not changed, we can keep it.
3. The Vector configuration issue is moved to #1407
