### ISSUE TITLE
Update docs for feat: add GRPC unary call service to our GreptimeDB

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/docs#258]
A document change request is generated from
https://github.com/GreptimeTeam/greptimedb/pull/1196

**Comment by MichaelScofield** [comment]
should also add back grpc reflection contents. related:
- https://github.com/GreptimeTeam/docs/pull/201
- https://github.com/GreptimeTeam/docs/pull/199
- https://github.com/GreptimeTeam/docs/pull/175
