### ISSUE TITLE
Add notes for table name that contain uppercase letters

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/docs#433]
When querying table that has uppercase letter in its name, it results in following error.

```
{
    "code": 3000,
    "error": "Query engine output error: Failed to execute query: select distinct instance from node_memory_HugePages_Total, source: Failed to plan statement, source: Cannot plan SQL: SELECT DISTINCT instance FROM node_memory_HugePages_Total, source: Error during planning: Table not found: greptime.public.node_memory_hugepages_total",
    "execution_time_ms": 1
}
```

To resolve this, we will have to add single quote to table name: `select distinct instance from 'node_memory_HugePages_Total'`

**Comment by killme2008** [comment]
Already has a note in compatibility doc, but it must be noted in the user guide @nicecui 

https://docs.greptime.com/reference/sql/compatibility#ansi-compatibility
