### ISSUE TITLE
Is Primary key related to tag ?

### ISSUE THREAD

**Issue by bigreybear** [GreptimeTeam/docs#452]
Hi, I am very interested in Greptime and going to take a try myself. 

But I  am still confused about how to set tag. Is it related to the primary key ? I didn't find any doc about it. 

Thank you

**Comment by nicecui** [comment]
Hi, PRIMARY KEY indicates the `Tag` type in the data model of GreptimeDB.

We have rewrote the documentations about data model and `CREATE` statement, please refer to [Data Model](https://docs.greptime.com/user-guide/concepts/data-model), [Table management](https://docs.greptime.com/user-guide/table-management#create-table) and [`CREATE` statement](https://docs.greptime.com/reference/sql/create#table-constraints)

If you still have any questions please let us know.
