### ISSUE TITLE
more contents of time data type

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/docs#517]
about how to use the following data types:

* timestamp
* date

**Comment by alili** [comment]
It looks that we have ['Date', 'DateTime', 'Timestamp', 'TimestampMillisecond', 'TimestampMicrosecond', ''TimestampNanosecond'] as types for time.

we should let developers know that how to use this types for query and insert

**Comment by nicecui** [comment]
https://docs.greptime.com/reference/sql/data-types/#date-and-time-types-1
