### ISSUE TITLE
GreptimeDB is available on FreeBSD

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/docs#809]
I've added the FreeBSD port: https://cgit.freebsd.org/ports/tree/databases/greptimedb

Maybe you can add it to the list of systems where GreptimeDB is available?

The command to install it is: ```pkg install greptimedb```

_Originally posted by @yurivict in https://github.com/GreptimeTeam/greptimedb/issues/3308#issuecomment-1951455346_

**Comment by tisonkun** [comment]
Some related pages:

* https://greptime.com/download
* https://greptime.com/resources#Download
* https://docs.greptime.com/getting-started/installation/greptimedb-standalone

We can add a "Package Manager" section to list out these opinions, while mentioning that they are community maintained instead of endorsed by Greptime Inc.

cc @nicecui

**Comment by sunng87** [comment]
Sounds good to me

**Comment by yurivict** [comment]
Based on [Repology](https://repology.org/projects/?search=greptimeDB) Arch also has a port for GreptimeDB.

Repology page will automatically update if/when other distros would create ports as well.

There are only 2 for now.

You can also reach out to the mailing lists of various distros and they'd possibly create the ports, in case you are interested.

**Comment by tisonkun** [comment]
FYI @yurivict I'm preparing a patch to update https://greptime.com/download to contain this package manager download source. The repo is private and I'll let you know when the patch is landed.

BTW, GreptimeDB v0.7.0 is formally released, you may package a new version based on this stable tag.

**Comment by tisonkun** [comment]
<img width="1341" alt="image" src="https://github.com/GreptimeTeam/docs/assets/18818196/6864a3c6-7670-4a97-b41a-1717a7c79fd7">

Done.
