### ISSUE TITLE
Clarify greptimedb's supported functions

### ISSUE THREAD

**Issue by MichaelScofield** [GreptimeTeam/docs#814]
Now the "[Functions](https://docs.greptime.cn/reference/sql/functions)" page is a little too fuzzy. It's hard for user to browser what functions greptimedb support. At lease when I want to find the UDAFs, I have to go with the source code. So I think a total refactor with function page is necessary that:
- separate greptimedb's UDF/UDAF from datafusion's, list them explicitly
- we can still link to datafusion's site for its supported functions
- maybe better use tables for displaying all the functions? Tables are compact, good for eyes.
- write examples for all our own functions
- create a sub-page for "python script as function", and "use function in python script"
- write the doc for "how to write a UDF/UDAF in greptimedb" as a sub page, or put it elsewhere then link it

**Comment by killme2008** [comment]
Fixed #1049
