### ISSUE TITLE
Add demo illustrations for node and tables

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/docs#842]
We have an example illustrations collection file - https://github.com/GreptimeTeam/docs/blob/main/docs/example.drawio.svg

It's good to use and formalize our draws. However, I found two common concepts are missing here.

Maybe our current illustrations can already cover them, but perhaps some concrete examples help.

cc @zhaoyingnan01 @nicecui 

### Node

We have metasrv, frontend, datanode, and other nodes. We'd better design a node illustration for them.

![image](https://github.com/GreptimeTeam/docs/assets/18818196/61fc489c-1dd9-47a1-8670-e356ff89872b)

* https://www.cockroachlabs.com/docs/stable/architecture/reads-and-writes-overview

### Table/Measurement

Another basic concept.

We may currently use this one:

<img width="1258" alt="image" src="https://github.com/GreptimeTeam/docs/assets/18818196/60985f4b-1237-43f8-bcf5-948029e39933">

... while I'm thinking of:

* https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/concepts/dynamic_tables/

**Comment by nicecui** [comment]
The priority is low. We can reopen this issue in the future.
