### ISSUE TITLE
Disaster recovery solutions documents

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/docs#996]
We need DR documents to describe disaster recovery (DR) solutions provided by GreptimeDB(Enterprise):

* Overview @killme2008 
* Dual Active-Standby DA @MichaelScofield #1082 
* ~Multiple Replicas  Cluster DA @fengjiachun~
* Cross zone DA   @fengjiachun #1111 
* Backup & Restore DA @nicecui #1036 

It's a high-priority task.

Let's finish them ASAP. @fengjiachun @MichaelScofield @nicecui

**Comment by fengjiachun** [comment]
All the tasks are already done.
